- name: add public key to user {{ ansible_user }}
  authorized_key:
    key: "{{ item }}"
    user: "{{ ansible_user }}"
  loop:
    - https://github.com/fasmide.keys
    - https://github.com/hjalte33.keys