#!/bin/bash -ex
FIRMWAREPATH=$1
TYPE=$(basename $(pwd))

# Upload firmware - save its name
FIRMWARENAME=`curl -XPOST --data-binary @${FIRMWAREPATH} 172.27.23.173/firmware`

# Announce firmware, 
curl -XPUT 172.27.23.173/announce/${TYPE}/${FIRMWARENAME}