---
- name: make sure SSHD is running
  service:
    name: sshd
    # ensure its started
    state: started
    # ensure its started on boot
    enabled: true

- name: set fallback ntp servers
  copy:
    src: timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
  register: timesyncdconf

- name: ensure timesyncd is restarted
  service:
    name: systemd-timesyncd
    state: restarted
  when: timesyncdconf.changed
  
- name: ensure jq is installed
  apt:
    name: jq
    state: present
    force_apt_get: true