http:
  routers:
    grafana-dev-case:
      rule: "Host(`grafana.dev-case.idl.mp.aau.dk`)"
      service: grafana-dev-case
      tls:
        certResolver: sample
    redirecttohttps:
      entryPoints: 
        - web
      rule: "HostRegexp(`{host:.+}`)"
      service: noop
      middlewares: 
        - httpsredirect

  services:
    noop:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:80/
    grafana-dev-case:
      loadBalancer:
        servers:
          - url: "http://10.14.47.2:3000/"

  middlewares:
    httpsredirect:
      redirectScheme:
        scheme: https