http:
  routers:
    grafana-dev-case:
      rule: "Host(`grafana.dev-case.idl.mp.aau.dk`)"
      service: grafana-dev-case
      tls:
        certResolver: sample
    api-dev-case:
      rule: "Host(`api.dev-case.idl.mp.aau.dk`)"
      service: api-dev-case
      tls:
        certResolver: sample
      middlewares:
        - api-auth
    grafana-second-case:
      rule: "Host(`grafana.second-case.idl.mp.aau.dk`)"
      service: grafana-second-case
      tls:
        certResolver: sample
    api-second-case:
      rule: "Host(`api.second-case.idl.mp.aau.dk`)"
      service: api-second-case
      tls:
        certResolver: sample
      middlewares:
        - api-auth
    redirecttohttps:
      entryPoints: 
        - web
      rule: "HostRegexp(`{host:.+}`)"
      service: noop
      middlewares: 
        - httpsredirect

  services:
    noop:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:80/
    grafana-dev-case:
      loadBalancer:
        servers:
          - url: "http://10.14.47.2:3000/"
    api-dev-case:
      loadBalancer:
        servers:
          - url: "http://10.14.47.2:9090/"
    grafana-second-case:
      loadBalancer:
        servers:
          - url: "http://10.14.47.3:3000/"
    api-second-case:
      loadBalancer:
        servers:
          - url: "http://10.14.47.3:9090/"

  middlewares:
    httpsredirect:
      redirectScheme:
        scheme: https
    api-auth:
      basicAuth:
        users:
          - "apiuser:$2y$05$.KY1FbgZLgLxN.BIdyWuk.Y08CkBJciyMA9aBUFAk6LCwr2eFL22O"