---
- name: install hostapd
  apt:
    # rasbian does not have aptitude
    force_apt_get: true
    name: hostapd
    state: present

- name: configure hostapd
  copy:
    src: hostapd.conf
    dest: /etc/hostapd/hostapd.conf
  register: hostapdconf

- name: enable hostapd
  service:
    name: hostapd
    masked: false
    enabled: true
    state: started

- name: (re)start hostapd
  service:
    name: hostapd
    state: restarted
  when: hostapdconf.changed

- name: set wlan0 configuration
  copy:
    src: wlan0.network
    dest: /etc/systemd/network/wlan0.network

- name: set eth0 configuration
  copy:
    src: eth0.network
    dest: /etc/systemd/network/eth0.network

- name: remove ifupdown (included with raspbian)
  apt:
    name: ifupdown
    state: absent

# dhcpcd conflicts with networkd
- name: disable dhcpcd
  service:
    name: dhcpcd
    state: stopped
    masked: true

- name: enable networkd
  service:
    name: systemd-networkd
    state: started
    enabled: true

- name: install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: configure dnsmasq
  copy:
    src: wlan0.dnsmasq.conf
    dest: /etc/dnsmasq.d/wlan0.conf
  register: hostapddnsmasq

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
  when: hostapddnsmasq.changed