---
- name: install wireguard device
  template:
    src: wg0.netdev.j2
    dest: /etc/systemd/network/wg0.netdev
  register:
    wireguardDevice
    
- name: install wireguard network configuration
  template:
    src: wg0.network.j2
    dest: /etc/systemd/network/wg0.network
  register:
    wireguardNetwork

- name: restart networkd when changed
  service:
    name: systemd-networkd.service
    state: restarted
  when: wireguardDevice.changed == True or wireguardNetwork.changed == True

- name: ensure ufw is installed
  apt:
    name: ufw
    state: present
    force_apt_get: true

- name: "ufw: drop everything incoming"
  ufw:
    direction: incoming
    default: reject

- name: "ufw: accept everything outgoing"
  ufw:
    direction: outgoing
    default: allow

- name: "ufw: allow everything on wg0"
  ufw:
    direction: in
    interface: wg0
    rule: allow

- name: "ufw: allow everything on wlan0"
  ufw:
    direction: in
    interface: wlan0
    rule: allow

- name: "ufw: enable ufw"
  ufw:
    state: enabled
