---
- name: takeover getty@tty1
  copy:
    src: getty-override.conf
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
  register: dashgettyoverride

- name: upload dash binary
  copy:
    src: dash-arm-build
    dest: /home/pi/dash
  register: dashbinary

- name: restart getty@tty1.service
  service:
    name: getty@tty1.service
    state: restarted
    daemon_reload: true
  when: dashbinary.changed or dashgettyoverride.changed
