---
- name: add wireguard repository
  apt_repository:
    repo: ppa:wireguard/wireguard

- name: install wireguard
  apt:
    name: wireguard
    state: present
    force_apt_get: true

- name: create directory for case wg-keys
  file:
    path: /etc/systemd/network/keys/
    state: directory

- name: Store wg public key file for each reachable case
  copy:
    dest: "/etc/systemd/network/keys/{{ hostvars[item].wg0_ip_address }}" # wg0_ip_address is not necessarily the same ip as "item"
    content: |
      {{ hostvars[item].wg0.public_key }}

  when: hostvars[item].wg0.public_key is defined # skip cases that are not online
  loop: "{{ groups['case'] }}"

- name: Read wg public key files back to include cases that are currently offline
  slurp:
    src: "/etc/systemd/network/keys/{{ hostvars[item].wg0_ip_address }}"
  register: slurpfile
  loop: "{{ groups['case'] }}"

- name: install wireguard device
  template:
    src: wg0.netdev.j2
    dest: /etc/systemd/network/wg0.netdev
  register:
    wireguardDevice

- name: install wireguard network configuration
  copy:
    src: wg0.network
    dest: /etc/systemd/network
  register:
    wireguardNetwork

- name: restart networkd when changed
  service:
    name: systemd-networkd.service
    state: restarted
  when: wireguardDevice.changed == True or wireguardNetwork.changed == True