---
- name: add wireguard repository
  apt_repository:
    repo: ppa:wireguard/wireguard

- name: install wireguard
  apt:
    name: wireguard
    state: present
    force_apt_get: true

- name: Creating wg key file for each case
  copy:
    dest: "/etc/systemd/network/keys/{{ item.wg0_ip_address}}"
    content: |
      "{{ item.wg0.public_key }}"
  loop:
    "{{ groups:['case'] }}"    

- name: install wireguard device
  template:
    src: wg0.netdev.j2
    dest: /etc/systemd/network/wg0.netdev
  register:
    wireguardDevice

- name: install wireguard network configuration
  copy:
    src: wg0.network
    dest: /etc/systemd/network
  register:
    wireguardNetwork

- name: restart networkd when changed
  service:
    name: systemd-networkd.service
    state: restarted
  when: wireguardDevice.changed == True or wireguardNetwork.changed == True