all:
  children:
    cloud:
      hosts:
        130.225.57.82:
          ansible_user: ansible
          ansible_become: yes
          ansible_ssh_common_args: -o UserKnownHostsFile=/known_hosts
          ansible_python_interpreter: /usr/bin/python3
    case:
      hosts:
        10.14.47.2:
          ansible_user: pi
          ansible_become: yes
          ansible_ssh_common_args: -F ssh_config
          ansible_python_interpreter: /usr/bin/python3
