all:
  children:
    cloud:
        hosts:
    case:
        hosts:
          172.27.23.173:
            ansible_user: pi
            ansible_become: yes
            ansible_ssh_private_key_file: id_rsa
            ansible_ssh_common_args: -o UserKnownHostsFile=known_hosts
