---
- hosts:
  - case
  - cloud
  roles:
    - { name: gatherkeys, tags: gatherkeys }

- hosts: 
  - case
  roles:
    - { name: vpnclient, tags: vpnclient }

- hosts: 
  - cloud
  roles:
    - { name: vpnserver, tags: vpnserver }