---
- name: add telenor.service
  copy:
    src: telenor.service
    dest: /etc/systemd/system/telenor.service

- name: add wwan0 device
  copy:
    src: wwan0.network
    dest: /etc/systemd/network/wwan0.network
    